name: cwbplot
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - basemap
  - cartopy
  - proplot
  - pygrib
  - basemap-data-hires
