#!/bin/bash
set -ex

whichpy=`which python`
echo ${whichpy}


mkdir "${whichpy}/cwbplot"

wget "https://github.com/Liu-CWB/cwbplot/archive/refs/heads/master.zip" -P "${HOME}"
unzip "${HOME}/master.zip"
cp ${HOME}/cwbplot-master/*.py "${whichpy}/cwbplot"
touch "${whichpy}/cwbplot/__init__.py"


id="1ZFhD09eGupUqJsCyvr9cC5YFgeweov0O"
outname="M-A0064-21072000-072.grb2"
confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id='$id -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
echo $confirm
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$confirm&id=$id" -O $outname && rm -rf /tmp/cookies.txt

id="1wgIwqrO998X6wmbDnBLKGnG6bIDR1lMM"
outname="M-A0064-21072000-084.grb2"
confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id='$id -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
echo $confirm
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$confirm&id=$id" -O $outname && rm -rf /tmp/cookies.txt
